<?php
    $db=mysqli_connect("localhost","root","","school_management");
    $date = date("d-m-y");
    $id = $_GET['id'];
    $count = "SELECT * FROM result WHERE student_id='$id'";
    $queryResult= mysqli_query($db,$count);
    $p = mysqli_fetch_assoc($queryResult);
    $avg=($p['banglaGPA']+$p['englishGPA']+$p['mathematicsGPA']+$p['scienceGPA']+$p['religionGPA'])/5;

    require('fpdf/fpdf.php');
    $pdf = new FPDF();
    $pdf->AddPage($pdf->SetFillColor(235, 236, 236));
    $pdf->SetFont("Arial", "", 10);
    $pdf->Image('logo.jpeg',55,15,-350);
    $pdf->Cell(0, 10, 'Page '.$pdf->PageNo(), 0, 1, 'R');
    $pdf->SetFont("Arial", "B", 16);
    $pdf->SetFillColor(235, 236, 236);
    $pdf->Cell(0, 10, "Dream School", 0, 1, 'C');
    $pdf->Ln(8);
    $pdf->SetFont("Arial", "", 14);
    $pdf->Cell(170, 10, "Date:", 0, 0, 'R');
    $pdf->Cell(0, 10, "$date", 0, 1, 'R');
    $pdf->Ln(3);
    $pdf->SetFont("Arial", "I", 14);
    $pdf->SetTextColor(255, 0, 0);
    $pdf->Cell(90, 10, "Name :", 1, 0, 'C');
    $pdf->Cell(100, 10, "$p[student_name]", 1, 1, 'C');
    $pdf->Cell(90, 10, "Roll :", 1, 0, 'C');
    $pdf->Cell(100, 10, "$p[roll_no]", 1, 1, 'C');
    $pdf->Cell(90, 10, "Class :", 1, 0, 'C');
    $pdf->Cell(100, 10, "$p[class]", 1, 1, 'C');
    $pdf->Ln(10);
    $pdf->SetFont("Arial", "B", 16);
    $pdf->SetFillColor(30,150,235);
    $pdf->SetTextColor(255, 255, 255);
    $pdf->Cell(0, 10, "Result", 1, 1, 'C',true);
    $pdf->Ln(3);
    $pdf->SetTextColor(0, 0, 0);
    $width_cell = array(90,50,50);
    $pdf->SetFont("Arial", "B", 14);
    $pdf->SetFillColor(193, 229, 252);
    $pdf->Cell($width_cell[0], 10, 'Subject Name', 1, 0, 'C', true);
    $pdf->Cell($width_cell[1], 10, 'Grade', 1, 0, 'C', true);
    $pdf->Cell($width_cell[2], 10, 'GPA', 1, 1, 'C', true);
    $pdf->SetFont("Arial", "B", 12);
    $pdf->SetFillColor(235, 236, 236);
    $pdf->Cell($width_cell[0], 10, "Bangla", 1, 0, 'C', true);
    $pdf->Cell($width_cell[1], 10, "$p[bangla]", 1, 0, 'C', true);
    $pdf->Cell($width_cell[2], 10, "$p[banglaGPA]", 1, 1, 'C', true);
    $pdf->Cell($width_cell[0], 10, "English", 1, 0, 'C', true);
    $pdf->Cell($width_cell[1], 10, "$p[english]", 1, 0, 'C', true);
    $pdf->Cell($width_cell[2], 10, "$p[englishGPA]", 1, 1, 'C', true);
    $pdf->Cell($width_cell[0], 10, "Mathematics", 1, 0, 'C', true);
    $pdf->Cell($width_cell[1], 10, "$p[mathematics]", 1, 0, 'C', true);
    $pdf->Cell($width_cell[2], 10, "$p[mathematicsGPA]", 1, 1, 'C', true);
    $pdf->Cell($width_cell[0], 10, "Science", 1, 0, 'C', true);
    $pdf->Cell($width_cell[1], 10, "$p[science]", 1, 0, 'C', true);
    $pdf->Cell($width_cell[2], 10, "$p[scienceGPA]", 1, 1, 'C', true);
    $pdf->Cell($width_cell[0], 10, "Religion", 1, 0, 'C', true);
    $pdf->Cell($width_cell[1], 10, "$p[religion]", 1, 0, 'C', true);
    $pdf->Cell($width_cell[2], 10, "$p[religionGPA]", 1, 1, 'C', true);
    $pdf->Ln(3);
    $pdf->SetFont("Arial", "B", 16);
    $pdf->SetFillColor(30,150,235);
    $pdf->SetTextColor(255, 255, 255);
    $pdf->Cell(0, 10, "Total GPA : $avg", 1, 1, 'C',true);
    $pdf->Output();
    ?>
